config/routes.rb
Rails.application.routes.draw do
    
    root 'pages#home'
    
    get '/home', to: 'pages#home'
    
   # get '/trips', to: 'trips#index'
   # get '/trips/new', to: 'trips#new', as: 'new_trip'
   # post '/trips', to: 'trips#create'
   # get '/trips/id:edit', to: 'trips#edit', as: 'edit_trip'
   # patch '/trips/:id', to: 'trips#update'
   # get 'trips/:id', to: 'trips#show', as: 'trip'
   # delete '/trips/:id', to: 'trips#destroy'
    
    resources :trips do # Embedding the likes and 
       member do 
           post 'like'
       end
    end
    
    
    resources :travellers, except: [:new]
    
    get '/register', to: 'travellers#new'
    
    get '/login', to: "logins#new"
    post '/login', to: "logins#create"
    get '/logout', to: "logins#destroy"
    
    
    #login -> new session
    #logout -> close session
    #post login -> create session
    
end

app/models/like.rb
class Like < ActiveRecord::Base
   belongs_to :traveller
   belongs_to :trip
   
   validates_uniqueness_of :traveller, scope: :trip #Allowing like once to one trip / 
end

app/models/traveller.rb
class Traveller < ActiveRecord::Base
    has_many :trips
    has_many :likes
    before_save { self.email = email.downcase } # Before saving to DB , email is converted to downcase
    validates :travellername, presence: true, length: { minimum: 3, maximum: 40 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
                                      uniqueness: { case_sensitive: false },
                                      format: { with: VALID_EMAIL_REGEX }
                                      
    has_secure_password 
end

app/models/trip.rb
class Trip < ActiveRecord::Base
    belongs_to :traveller
    has_many :likes
    validates :traveller_id, presence: true
    validates :name, presence: true, length: { minimum: 5,  maximum: 100 }
    validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
    validates :description, presence: true, length: { minimum: 20, maximum: 500 }
    mount_uploader :picture, PictureUploader 
    validate :picture_size 
    default_scope -> { order(updated_at: :desc)} # Ordering by date rather than likes. / If I want to omplement order by likes ill add new table to likes table with increment.
    
    def thumbs_up_total
       self.likes.where(like: true).size 
    end
    
    def thumbs_down_total
        self.likes.where(like: false).size
    end
    
    private
        def picture_size
            if picture.size > 5.megabytes
                errors.add(:picture, "should be less than 5MB")
            end
        end
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= Traveller.find(session[:traveller_id]) if session[:traveller_id] #Memoisation / reusing instance variables || storing session to current user, wont look again.
    #efficiency
  end
  
  def logged_in? # Checking !! Boolean return
    !!current_user
  end
  
  def require_user
    if !logged_in?
        flash[:danger] = "You must be logged in to perform that action"
        redirect_to :back
    end
  end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    
    def new
            
    end
    
    def create
        traveller = Traveller.find_by(email: params[:email])
        if traveller && traveller.authenticate(params[:password])
            session[:traveller_id] = traveller.id 
            flash[:success] = "You are logged in"
            redirect_to trips_path
        else
           flash.now[:danger] = "Your email address or password does not match" 
           render 'new'
        end
    end
    
    def destroy
        session[:traveller_id] = nil
        flash[:success] = "You have logged out"
        redirect_to trips_path
    end
       
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home 
        redirect_to trips_path if logged_in?
    end
end

app/controllers/travellers_controller.rb
class TravellersController < ApplicationController
    before_action :set_traveller, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update] #executed in order
    
    def index
        @travellers = Traveller.paginate(page: params[:page], per_page: 3)
    end
    
    def new 
        @traveller = Traveller.new # Instance variable
    end
    
    
    def create
        @traveller = Traveller.new(traveller_params)
        if @traveller.save # Give a success message - flash
            flash[:success] = "Your account has been created successfully"
            session[:traveller_id] = @traveller.id
            redirect_to trips_path
        else
            render 'new'
        end
    end
    
    
    def edit
    
    end
    
    
    def update
        if @traveller.update(traveller_params)
            flash[:success] = "Your Profile has been updated succesfully"
            redirect_to traveller_path(@traveller)
        else
            render 'edit'
        end
    end
    
    def show
        @trips = @traveller.trips.paginate(page: params[:page], per_page: 3)
    end
    
    private
    
    def traveller_params
        params.require(:traveller).permit(:travellername, :email, :password)
    end
    
    def set_traveller
        @traveller = Traveller.find(params[:id])
    end
    
    def require_same_user
        if current_user != @traveller
            flash[:danger] = "You can only edit your own profile"
            redirect_to root_path
        end
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
   before_action :set_trip, only: [:edit, :update, :show, :like]
   before_action :require_user, except: [:show, :index]
   before_action :require_same_user, only: [:edit]
   
   def index
      @trips = Trip.paginate(page: params[:page], per_page: 4)
       # Sorting the posts by amount of likes
       #@trips = Trip.all.sort_by{|likes| likes.thumbs_up_total}.reverse #From most to least (.reverse) 
   end
    
   def show
      
   end
   
   def new
      @trip = Trip.new
   end
   
   def create
      @trip = Trip.new(trip_params) #STRONG PARAMS RAILS 4 - Explicitly List the params which can be accepted
      @trip.traveller = current_user #here<-Causing same user
      
      if @trip.save
         #do something
         flash[:success] = "You Shared your trip successfully!"
         redirect_to trips_path
      else
         render :new
      end
   end
   
   
   def edit
   end
   
   
   
   def update
      if @trip.update(trip_params)
         
         flash[:success] = "Your Trippic was updated successfully!"
         redirect_to trip_path(@trip)
      else
         render :edit
      end
   end
   
   def like
      like = Like.create(like: params[:like], traveller: current_user, trip: @trip)
      
      if like.valid? # Showing messsage to user that you have already voted and you new vote has not been counted
         flash[:success] = "Your selection was successful"
         redirect_to :back
      else
         flash[:danger] = "You can only like/dislike a Trippic once"
         redirect_to :back
      end
   end
   
      private
      
      def trip_params
         params.require(:trip).permit(:name, :summary, :description, :picture) #Adding Picture param
      end
      
      def set_trip
        @trip = Trip.find(params[:id]) 
      end
      
      def require_same_user
         if current_user != @trip.traveller
            flash[:danger] = "You can only edit your own trips"
            redirect_to trips_path
         end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(traveller, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(traveller.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: traveller.travellername, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <p> Trippic 2015 </p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class"col-md-10">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "Trippic", root_path, class: "btn btn-lg btn-primary", id: "logo" %>


      <% if logged_in? %>
        <div class="nav_item">
          <%= link_to "New Trippic", new_trip_path, class: "btn btn-default btn-success" %>
        </div>
        <ul class="nav_item">
          <li class="dropdown">
            <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle ", "data-toggle" => "dropdown" do %>
             <%= current_user.travellername %> <b class-"caret"></b>
            <% end %>
            <ul class='dropdown-menu'>
              <li><%= link_to "View Profile", traveller_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_traveller_path(current_user)%></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", logout_path %></li>
            </ul>
          </li>
        </ul>
        <% else %>
        <div class="nav_item">
          <%= link_to "Log In", login_path, class: "btn btn-default btn-success" %>
        </div>
        <%end%>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trippic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    
    <%= render 'layouts/footer' %>
    
  </div>
</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'log in' %>

<div class="row">
    <div class="well col-md-6 col-md-offset-3">
        <%= form_tag '/login' do %>
        
        <%= label_tag :email %>
        <%= text_field_tag :email %>
            
        <%= label_tag :password %>
        <%= password_field_tag :password %>
            
        <%= submit_tag 'Login', class: 'btn btn-success' %>
            
    
        <% end %>
    </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1> Welcome to Trippic App</h1>
    
    <h2>
        
        <p> The Idea of the Trippic App is to allow users to share their experiances and best tips and advice about visiting various destinations around the world
        whilst also sharing a single photo which emcompasses their entire trip</p>
    </h2>
    
    <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
</div>
<div class="row">
    <div class="col-lg-4">
        <h3 class="midrow">
            View Trippics as Guest user
        </h3>
        <h2 class="left">Browse and view trippics as a guest and Sign Up later</h2>
        <p><%= link_to "Browse Trippics", trips_path, class: "btn btn-warning btn-small" %></p>
    </div>
    <div class="col-lg-4">
        <h3 class="midrow">
            Sign into your account
        </h3>
        <h2 class="left">Add/Update your Trippics / Create Reviews/ Like & Dislike Trippics </h2>
        <p><%= link_to "Login to your account", login_path,  class: "btn btn-warning btn-small" %></p>
    </div>
    <div class="col-lg-4">
        <h3 class="midrow">
            View Trippics as Guest user
        </h3>
        <h2 class="left">Browse and view trippics as a guest and Sign Up later</h2>
        <p><%= link_to "Browse Trip Listings", trips_path, class: "btn btn-warning btn-small" %></p>
    </div>
</div>
<hr/>

<%# https://developers.google.com/maps/tutorials/fundamentals/adding-a-google-map %>
<style>
      #map {
        width: 100%;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map');
        var mapOptions = {
          center: new google.maps.LatLng(44.5403, -78.5463),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

<h1>Wheres Your Next Trip??</h1>
<div id="map"></div>

    

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="alert alert-danger col-md-8 col-md-offset-2">
            <h5> Please correct the following errors:</h5>
            <ul>
                <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
    <h1><%= title %></h1>
    <hr/>
</p>

app/views/travellers/_form.html.erb
<%= render 'shared/errors', obj: @traveller %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
    <%= form_for @traveller do |f| %> 
        <%= f.label :travellername %>
        <%= f.text_field :travellername %>
        
        <%= f.label :email %>
        <%= f.email_field :email %>
        
        <%= f.label :password %>
        <%= f.password_field :password %> <%# Star out the password %>
        
        <%# New Record Boolean %>
        <%= f.submit(@traveller.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
        <%end%>
    </div>
</div>

app/views/travellers/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile" %>



<%= render 'form' %>
<%# Rendering form instead of having redundant code %>

app/views/travellers/index.html.erb
<%= render 'shared/page_title', title: "All travellers" %>

<ul class="nav nav-tabs"> <%# Navigation on Travellers page %>
    <li>
        <%= link_to "Trips", trips_path %>
    </li>
    <li class='active'>
        <%= link_to "Travellers", travellers_path %>
    </li>
</ul>


<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate %>
    </div>
</div>

<% @travellers.each do |traveller| %>
    <div class="row">
        <div class="col-md-4 col-md-offset-4 center">
        <%= link_to gravatar_for(traveller, size: 200), traveller_path(traveller) %>
        <p>
            <h5> Traveller name: <%= traveller.travellername %></h5>
        </p>
        </div>
    </div>

<% end %>

app/views/travellers/new.html.erb
<%= render 'shared/page_title', title: "Register your account" %>



<%= render 'form' %>
<%# Rendering form instead of having redundant code %>

app/views/travellers/show.html.erb
<%= render 'shared/page_title', title: "Traveller: " + @traveller.travellername %>


<div class="row">
    <div class="col-md-4 col-md-offset-4 center"> 
        <%= gravatar_for @traveller, size:200 %>
        <hr/>
    </div>
</div>



<div class="row">
    <div class="col-md-4 col-md-offset-4 center"
    <h3><em> Trips:</em></div></h3>
    <%= will_paginate @trips %>
</div>
    
<% @trips.each do |trip| %>
    <div class="row">
     <div class="col-lg-6 well col-lg-offset-3">
        <h4><%= link_to trip.name, trip_path(trip) %></h4>
        <p><%= trip.summary %></p>
        <p> 
            <span class='quite'><small> created: <%= time_ago_in_words(trip.created_at) %> ago, </small></span> 
            <span class='quite'><small> updated: <%= time_ago_in_words(trip.updated_at) %> ago </small></span> 
        </p>
        <div class="pull-right">
            <%= link_to like_trip_path(trip, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= trip.thumbs_up_total %>
            <%end%> &nbsp&nbsp&nbsp&nbsp
            <%= link_to like_trip_path(trip, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= trip.thumbs_down_total %>
            <%end%>
         </div>
        </div>
    </div>
<%end%>

app/views/trips/_form.html.erb
<%= render 'shared/errors', obj: @trip %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@trip, html: { multipart:true }) do |f| %> <%# Adding image upload %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        
        <%= f.label :summary %>
        <%= f.text_field :summary %>
        
        <%= f.label :description %>
        <%= f.text_area :description, rows:10 %>
        
        <span class="picture">
            <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %> <%# Image uploading WHITE LISTING %>
        </span>
        
        <%# New Record Boolean %>
        <%= f.submit(@trip.new_record? ? 'Create Trippic' : 'Edit Trippic', class: "btn btn-success") %>
        <%end%>
    </div>
</div>


<script type="text/javascript">
    $('#trip_picture').bind('change', function() {
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file');
        }
    });
</script>

app/views/trips/edit.html.erb
<%= render 'shared/page_title', title: "Edit Trippic" %>


<%= render 'form' %>
<%# Rendering form instead of having redundant code %>

app/views/trips/index.html.erb
<%= render 'shared/page_title', title: "All Trippics" %>

<ul class="nav nav-tabs"> <%# Navigation on Trips page %>
    <li class='active'>
        <%= link_to "Trips", trips_path %>
    </li>
    <li>
        <%= link_to "Travellers", travellers_path %>
    </li>
</ul>

<%= will_paginate %>

<% @trips.each do |trip| %> <%# Iterating through each trip %>
    <div class="row">
        
        <div class="col-md-2">
            <section class="traveller_info center">
                <%= link_to gravatar_for(trip.traveller, size: 100), traveller_path(trip.traveller) %>
                <h5>Traveller Name: <%= trip.traveller.travellername %></h5>
            </section>
        </div>
        
        <div class="col-lg-6 well">
            <h4><%= link_to trip.name, trip_path(trip) %></h4>
            <p><%= trip.summary %></p>
            <p> 
                <span class='quite'><small> created: <%= time_ago_in_words(trip.created_at) %> ago, </small></span> 
                <span class='quite'><small> updated: <%= time_ago_in_words(trip.updated_at) %> ago </small></span> 

            </p>
            <div class="pull-right">
              <%= link_to like_trip_path(trip, like: true), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= trip.thumbs_up_total %>
              <%end%> &nbsp&nbsp&nbsp&nbsp
              <%= link_to like_trip_path(trip, like: false), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= trip.thumbs_down_total %>
              <%end%>
          </div>
        </div>
        <div class="col-md-4"> <%# trip.picture single due o iteration %>
            <%= image_tag(trip.picture.url, size:"250x150", class: "gravatar") if trip.picture? %> <%#return true if picture and display %>
        </div>
        
    </div>
    <hr/>
<% end %>

<%= will_paginate %>

app/views/trips/new.html.erb
<%= render 'shared/page_title', title: "Create a new Trippic" %>



<%= render 'form' %>
<%# Rendering form instead of having redundant code %>

app/views/trips/show.html.erb
<%= render 'shared/page_title', title: @trip.name %>

<div class="row">
    <div class="col-md-4 pull-right center">
        <%= link_to gravatar_for(@trip.traveller, size:200), traveller_path(@trip.traveller) %>
        <p>
            <h5> Invisioned to you by: <%= @trip.traveller.travellername %></h5>
        </p> 
    </div>
    
    
    <div class="col-md-8">
        <% if logged_in? and @trip.traveller == current_user %>
            <%= link_to "Edit this Trippic", edit_trip_path(@trip), class: "btn btn-success pull-right" %>
        <%end%>
        <h3><%= @trip.summary %></h3> 
        <div class="show_trip">
            <%= image_tag(@trip.picture.url, class: "gravatar") if @trip.picture? %>
        </div>
        <div class="well">
          <p>
              <strong>Trip Advice:</strong> 
          </p>  
          <%= simple_format(@trip.description) %>
          <div class="pull-right">
              <%= link_to like_trip_path(@trip, like: true), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @trip.thumbs_up_total %>
              <%end%> &nbsp&nbsp&nbsp&nbsp
              <%= link_to like_trip_path(@trip, like: false), method: :post do %>
                 <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @trip.thumbs_down_total %>
              <%end%>
          </div>
        </div>
    </div>
</div>

<h5><%= link_to 'Return to Trip Listing', trips_path, class: "btn btn-warning btn-small"%></h5>